export class UserDetails {
    constructor(
        public id: Number,
        public fname: String,
        public mname: String,
        public sname: String,
        public email: String,
        public cnumber: String,
        public no: String,
        public street: String,
        public city: String,
        public dob: String,
        public gender: String,
        public position: String,
        public occupation: String,
        public registrationType: String,
        public studingYear: String,
        public studingSemester: String,
        public paymentType: String,
        public paymentAmount: String,
        public medium: String,
        public subject: String,
        public active?: Number,
    ){}
}
